/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KindleImportPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/components/fileUploadModal.ts
var import_obsidian4 = require("obsidian");

// src/components/component-utils.ts
var ACCEPTED_EXTENSIONS = ["html", "pdf"];

// src/processing/export.ts
var import_obsidian2 = require("obsidian");

// src/processing/goodreads.ts
var import_obsidian = require("obsidian");
function getBookID(text) {
  const matches = text.match(/\/book\/show\/([A-Za-z0-9\-._]+)\?.*/);
  if (matches) {
    return matches[1];
  }
  console.log(`No book ID found in text: ${text}`);
  return void 0;
}
async function queryGoodreadsForBookID(bookTitle, authors) {
  const encodedQuery = encodeURIComponent(`${bookTitle} ${authors.join(" ")}`);
  const url = `https://www.goodreads.com/search?q=${encodedQuery}`;
  const response = await (0, import_obsidian.requestUrl)({ url });
  const parser = new DOMParser();
  const htmlDoc = parser.parseFromString(response.text, "text/html");
  const elements = htmlDoc.getElementsByClassName("bookTitle");
  if (elements.length === 0) {
    return void 0;
  }
  const elementHref = elements[0].getAttribute("href");
  if (!elementHref) {
    return void 0;
  }
  return getBookID(elementHref);
}

// src/processing/export.ts
function getMdFileTitle(bookTitle) {
  if (bookTitle.includes(":")) {
    return bookTitle.split(":")[0].trim();
  }
  return bookTitle.trim();
}
function highlightToQuoteString(highlight) {
  let titleLine;
  if (highlight.type === "note") {
    titleLine = "> [!note] Note";
  } else if (highlight.type === "quote") {
    if (highlight.pageNumber) {
      titleLine = `> [!quote] Quote (Page ${highlight.pageNumber})`;
    } else {
      titleLine = "> [!quote] Quote";
    }
  } else {
    throw new Error(`Invalid highlight type: ${highlight.type}`);
  }
  const textLine = highlight.text;
  return `${titleLine}
${textLine}`;
}
function stringifyBookHighlights(notebook, goodreadsBookID, goodreadsUserID) {
  const lines = [];
  lines.push("---");
  lines.push("tags:");
  lines.push("  - books");
  lines.push(`title: "${notebook.title}"`);
  lines.push("author:");
  notebook.authors.forEach((author) => {
    lines.push(`  - ${author}`);
  });
  lines.push("---");
  if (goodreadsBookID) {
    const bookURL = `https://www.goodreads.com/book/show/${goodreadsBookID}`;
    lines.push(`[${notebook.title}](${bookURL})`);
  } else {
    lines.push(notebook.title);
  }
  if (goodreadsUserID && goodreadsBookID) {
    const highlightsURL = `https://www.goodreads.com/notes/${goodreadsBookID}/${goodreadsUserID}`;
    lines.push(`[My Kindle Notes & Highlights](${highlightsURL})`);
  }
  lines.push("");
  lines.push(`Author: ${notebook.authors.join("; ")}`);
  lines.push("");
  lines.push("## Highlights");
  lines.push("");
  notebook.chapterHighlights.forEach((chapterHighlights) => {
    if (chapterHighlights.chapterName) {
      lines.push(`### ${chapterHighlights.chapterName}`);
      lines.push("");
    }
    chapterHighlights.highlights.forEach((highlight) => {
      lines.push(highlightToQuoteString(highlight));
      lines.push("");
    });
  });
  return lines.join("\n");
}
async function exportToMarkdown(notebook, app, settings) {
  const md_file_name = getMdFileTitle(notebook.title);
  let md_file_path;
  if (settings.exportLocation) {
    md_file_path = (0, import_obsidian2.normalizePath)(`${settings.exportLocation}/${md_file_name}.md`);
  } else {
    md_file_path = (0, import_obsidian2.normalizePath)(`${md_file_name}.md`);
  }
  if (app.vault.getAbstractFileByPath(md_file_path)) {
    new import_obsidian2.Notice("File already exists. Skipping export.");
    return;
  }
  let goodreadsBookID;
  if (settings.queryGoodreads) {
    goodreadsBookID = await queryGoodreadsForBookID(notebook.title, notebook.authors);
  }
  const text = stringifyBookHighlights(notebook, goodreadsBookID, settings.goodreadsUserID);
  app.vault.create(md_file_path, text);
  if (settings.queryGoodreads && !goodreadsBookID) {
    new import_obsidian2.Notice("No Goodreads book ID found. Check the console for more information.");
  }
  new import_obsidian2.Notice(`Exported notes for ${notebook.title}`);
}

// src/processing/parser/parser-utils.ts
function processAuthorName(text) {
  if (text.includes(",")) {
    const nameComponents = text.split(",");
    if (nameComponents.length === 2) {
      return `${nameComponents[1].trim()} ${nameComponents[0].trim()}`;
    }
  }
  return text;
}
function parseAuthors(text) {
  return text.split(";").map(processAuthorName);
}

// src/processing/parser/html-parser.ts
function getElementValue(htmlDoc, className) {
  const elements = htmlDoc.getElementsByClassName(className);
  if (elements.length === 0) {
    throw Error(`Element ${className} not present.`);
  }
  const textContent = elements[0].textContent;
  if (!textContent) {
    throw Error(`Element ${className} is empty.`);
  }
  return textContent.trim();
}
function getPageNumber(text) {
  const matches = text.match(/Page (\d+)/);
  if (matches) {
    return Number(matches[1]);
  }
  return void 0;
}
function getNoteType(text) {
  if (text.startsWith("Highlight")) {
    return "quote";
  } else {
    return "note";
  }
}
function parseKindleHtml(text) {
  const parser = new DOMParser();
  const htmlDoc = parser.parseFromString(text, "text/html");
  const title = getElementValue(htmlDoc, "bookTitle");
  const authors = parseAuthors(getElementValue(htmlDoc, "authors"));
  const chapterHighlights = [];
  Array.from(htmlDoc.querySelectorAll(".sectionHeading,.noteText")).forEach((element) => {
    var _a, _b, _c;
    const className = element.className;
    if (className === "sectionHeading") {
      const chapterName = (_a = element.textContent) == null ? void 0 : _a.trim();
      if (!chapterName) {
        throw Error("Chapter name is empty.");
      }
      chapterHighlights.push({ chapterName, highlights: [] });
      return;
    }
    const chapter = chapterHighlights[chapterHighlights.length - 1];
    const noteTextContent = (_b = element.textContent) == null ? void 0 : _b.trim();
    if (!noteTextContent) {
      return;
    }
    const noteHeadingElement = element.previousElementSibling;
    const noteHeadingTextContent = (_c = noteHeadingElement == null ? void 0 : noteHeadingElement.textContent) == null ? void 0 : _c.trim();
    if (!noteHeadingTextContent || (noteHeadingElement == null ? void 0 : noteHeadingElement.className) !== "noteHeading") {
      return;
    }
    const pageNumber = getPageNumber(noteHeadingTextContent);
    chapter.highlights.push({
      text: noteTextContent,
      pageNumber,
      type: getNoteType(noteHeadingTextContent)
    });
  });
  return { title, authors, chapterHighlights };
}

// src/processing/parser/pdf-parser.ts
var import_obsidian3 = require("obsidian");
function isPdfTextItem(x) {
  return typeof x === "object" && x !== null && typeof x.str === "string";
}
async function extractPdfText(buffer) {
  const pdfjsLib = await (0, import_obsidian3.loadPdfJs)();
  const pdf = await pdfjsLib.getDocument(buffer).promise;
  const textItems = [];
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const textContent = await page.getTextContent();
    const items = textContent.items.filter(isPdfTextItem);
    textItems.push(...items.filter(isPdfTextItem).map((it) => it.str));
  }
  return textItems.map((s) => s.trim());
}
function getTitle(lines) {
  const title = lines.find((line) => line.trim() !== "");
  if (!title) {
    throw new Error("No title found in PDF text");
  }
  return title.trim();
}
function getAuthors(lines) {
  const byIdx = lines.findIndex((line) => line.toLowerCase().startsWith("by "));
  if (byIdx === -1) {
    throw new Error("No author found in PDF text");
  }
  return parseAuthors(lines[byIdx].replace(/^by\s+/i, "").trim());
}
function matchHighlightType(line) {
  const quoteRegex = /^Highlight \(Yellow\) \| Page \d+$/i;
  const noteRegex = /^Highlight \(Yellow\) and Note \| Page \d+$/i;
  if (quoteRegex.test(line)) {
    return "quote";
  }
  if (noteRegex.test(line)) {
    return "quote_and_note";
  }
  return void 0;
}
function matchPage(line) {
  const pageMatch = line.match(/Page (\d+)/i);
  return pageMatch ? parseInt(pageMatch[1], 10) : void 0;
}
function parsePdfTextLines(lines) {
  const filteredLines = lines.filter((line) => !/^\d+$/.test(line.trim())).filter((line) => !/^Page \d+$/i.test(line.trim()));
  const title = getTitle(filteredLines);
  const authors = getAuthors(filteredLines);
  const highlights = [];
  let i = 0;
  while (i < filteredLines.length) {
    const matchType = matchHighlightType(filteredLines[i]);
    if (!matchType) {
      i++;
      continue;
    }
    const pageNumber = matchPage(filteredLines[i]);
    i++;
    if (filteredLines[i].trim() === "") {
      i++;
    }
    const quoteLines = [];
    while (i < filteredLines.length && filteredLines[i].trim() !== "") {
      quoteLines.push(filteredLines[i]);
      i++;
    }
    highlights.push({
      text: quoteLines.join(" "),
      pageNumber,
      type: "quote"
    });
    if (matchType === "quote_and_note") {
      i++;
      const noteLines = [];
      while (i < filteredLines.length && filteredLines[i].trim() !== "" && !matchHighlightType(filteredLines[i])) {
        noteLines.push(filteredLines[i]);
        i++;
      }
      highlights.push({
        text: noteLines.join(" "),
        pageNumber,
        type: "note"
      });
    }
  }
  return {
    title,
    authors,
    chapterHighlights: [
      {
        highlights
      }
    ]
  };
}
async function parseKindlePdf(data) {
  const textData = await extractPdfText(data);
  return parsePdfTextLines(textData);
}

// src/components/fileUploadModal.ts
var FILE_PICKER_TRIGGER_DELAY_MS = 10;
var FileUploadModal = class extends import_obsidian4.Modal {
  constructor(app, settings) {
    super(app);
    this.settings = settings;
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.classList.add("kindle-import-hidden-modal");
    const fileInput = document.createElement("input");
    fileInput.type = "file";
    fileInput.accept = ACCEPTED_EXTENSIONS.map((ext) => `.${ext}`).join(",");
    fileInput.multiple = false;
    fileInput.addEventListener("change", async () => {
      var _a;
      const file = (_a = fileInput.files) == null ? void 0 : _a[0];
      if (file) {
        try {
          let notebook;
          if (file.name.endsWith(".pdf")) {
            const content = await file.arrayBuffer();
            notebook = await parseKindlePdf(content);
          } else {
            const content = await file.text();
            notebook = parseKindleHtml(content);
          }
          await exportToMarkdown(notebook, this.app, this.settings);
        } catch (error) {
          console.error("Error parsing Kindle file:", error);
          new import_obsidian4.Notice(`Failed to import Kindle highlights: ${error.message}`);
        }
      }
      this.close();
    });
    contentEl.appendChild(fileInput);
    fileInput.addEventListener("cancel", (_event) => {
      this.close();
    });
    setTimeout(() => fileInput.click(), FILE_PICKER_TRIGGER_DELAY_MS);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/components/folderSuggest.ts
var import_obsidian5 = require("obsidian");
var FolderSuggest = class extends import_obsidian5.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    return this.app.vault.getAllFolders(true).filter((folder) => folder.path.toLowerCase().includes(query.toLowerCase()));
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path);
  }
  selectSuggestion(folder) {
    this.inputEl.value = folder.path;
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/components/kindleSelectionModal.ts
var import_obsidian6 = require("obsidian");
var KindleSelectionModal = class extends import_obsidian6.SuggestModal {
  constructor(app, settings) {
    super(app);
    this.settings = settings;
  }
  // Returns all available suggestions.
  getSuggestions(query) {
    return this.app.vault.getFiles().filter((file) => ACCEPTED_EXTENSIONS.includes(file.extension)).filter((file) => file.path.startsWith(this.settings.notebooksLocation)).filter((file) => file.name.toLowerCase().includes(query.toLowerCase()));
  }
  // Renders each suggestion item.
  renderSuggestion(book, el) {
    el.createEl("div", { text: book.name });
  }
  // Perform action on the selected suggestion.
  onChooseSuggestion(file, _evt) {
    let notebookPromise;
    if (file.extension === "pdf") {
      notebookPromise = this.app.vault.readBinary(file).then(async (content) => {
        return await parseKindlePdf(content);
      });
    } else if (file.extension === "html") {
      notebookPromise = this.app.vault.cachedRead(file).then((content) => {
        return parseKindleHtml(content);
      });
    } else {
      new import_obsidian6.Notice("Unsupported file type. Please select a PDF or HTML file.");
      return;
    }
    notebookPromise.then((notebook) => {
      return exportToMarkdown(notebook, this.app, this.settings);
    }).catch((error) => {
      console.error("Error parsing Kindle file:", error);
      new import_obsidian6.Notice(`Failed to import Kindle highlights: ${error.message}`);
    });
  }
};

// src/settings/pluginSettings.ts
var DefaultSettings = {
  notebooksLocation: "default/",
  exportLocation: "",
  queryGoodreads: false
};

// main.ts
var KindleImportPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "import-from-file-picker",
      name: "Import Kindle notebook with file picker",
      callback: () => {
        new FileUploadModal(this.app, this.settings).open();
      }
    });
    this.addCommand({
      id: "import-from-vault",
      name: "Import Kindle notebook from vault",
      callback: () => {
        new KindleSelectionModal(this.app, this.settings).open();
      }
    });
    this.addSettingTab(new KindleImportPluginSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DefaultSettings, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var KindleImportPluginSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian7.Setting(containerEl).setName("Notebook location").setDesc("Path to notebook folder").addText((text) => {
      text.setPlaceholder("Enter the path").setValue(this.plugin.settings.notebooksLocation).onChange(async (value) => {
        this.plugin.settings.notebooksLocation = (0, import_obsidian7.normalizePath)(value);
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian7.Setting(containerEl).setName("Book notes location").setDesc("Path to book notes folder").addText((text) => {
      text.setPlaceholder("Enter the path").setValue(this.plugin.settings.exportLocation).onChange(async (value) => {
        this.plugin.settings.exportLocation = (0, import_obsidian7.normalizePath)(value);
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian7.Setting(containerEl).setName("Query Goodreads").setDesc("If checked, the plugin will query Goodreads to generate a link to the book page").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.queryGoodreads).onChange(async (value) => {
        this.plugin.settings.queryGoodreads = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.queryGoodreads) {
      new import_obsidian7.Setting(containerEl).setName("Goodreads user ID").setDesc("ID of your Goodreads user").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("Enter the user ID").setValue((_a = this.plugin.settings.goodreadsUserID) != null ? _a : "").onChange(async (value) => {
            this.plugin.settings.goodreadsUserID = value;
            await this.plugin.saveSettings();
          });
        }
      );
    }
  }
};

/* nosourcemap */